apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-2
  #namespace: devenv
spec:
  replicas: 5
  selector:
    matchLabels:
      tier: nginx
  template:
    metadata:
      labels:
        tier: nginx
    spec:
      containers:
      - name: nginx
        image: nginx