apiVersion: v1
kind: ReplicationController

metadata:
  name: myapp-rc
  labels:
    app:  myapp
    costcenter: america
    location: NA
    type: frontend

spec:
  template:

    metadata:
     name: myapp-rc
     labels:
        app:  myapp
        costcenter: america
        location: NA
        type: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  selector:
     matchLabels:
	    type: front-end