apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
   DB_HOST: mysql  #supports only encoded strings
   DB_NAME: root   #supports only encoded strings
   DB_PASS: passwd #supports only encoded strings