apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app:  myapp
    costcenter: america
    location: NA
    type: frontend

spec:
  containers:
    - name: nginx-container
      image: nginx
  serviceAccount: dashboard-sa